@startuml 02_orders_in_memory
hide empty description

header Orders in Memory

label Orders[
{{
    title Zero Orders
    hide empty description

    state "<null>" as order_0
}}

{{
    title One Order
    hide empty description

    state "Order-0" as order_0
}}

{{
    title Two Orders
    hide empty description

    state "Order-0" as order_0
    state "Order-1" as order_1
    order_0 -> order_1
}}

{{
    title More Than Two Orders
    hide empty description

    state "Order-0" as order_0
    state "Order-1" as order_1
    state "Order-n" as order_n
    order_0 -> order_1
    order_1 -right[dotted]> order_n
}}
]

@enduml