@startuml 05_insert_order_act
hide empty description

title Insert Order Activity Diagram

start

while (State) is (Insert.Order)
     if (is First Call?) then (Yes)
        if (Existing Orders?) then (Yes)
            :Request First;
        else (No)
            :Write to Addr 0
            Set Size to 1;
            stop
        endif
    else (No)
        if (Check Memory) then (Memory not Ready)
            :Clear Request;
        else (Memory Ready)
            if (Just Write?) then (Yes)
                :Write (OrderBook.Command) to end
                Increment Size by 1;
                stop
            else (No)
                if (Check Match) then (Yes)
                    if (At End of List) then (Yes)
                        :Append
                        Write to last Element
                        Save last element in Temp Variable (OrderBook.Command)
                        Just Write = True;
                    else (Not at End)
                        :Write OrderBook.Command to Address = i
                        Request a Read of Address = i + 1
                        Increment i by 1;
                    endif
                else (Read Next or Append)
                    if (More Elements to Read?) then (Yes)
                        :Request a Read of Address i + 1;
                    else (No More Elements)
                        :Append
                        Increase Number of Orders by 1;
                        stop
                    endif;
                endif
            endif
        endif
    endif
endwhile
stop

@enduml