@startuml 06_delete_order_state
hide empty description

title Delete Order State Machine

label DeleteOrder[
{{
    title Parameters
    state "Parameters" as parameters
        parameters: Scratch.FirstCall
        parameters: OrderBook.Command.OrderId
}}

{{
    title State Variables Used
    state "Variables" as variables
        variables: **[filter.states]** filter.state
        variables: [u32] Scratch.I
        variables: [bool] Scratch.JustWrite
        variables: [u32] number.of.orders
        variables: Memory.Command.Read Order Request
        variables: Memory.Command.Read Order Address
        variables: Memory.Command.Write Order Request
        variables: Memory.Command.Write Order Address
        variables: Memory.Command.order.slot.OrderId
        variables: Memory.Command.order.slot.Quantity
}}

{{
    hide empty description

[*] --> delete_order
state "Delete Order" as delete_order
    delete_order --> first_call: Scratch.FirstCall == True
    state "First Call" as first_call
        first_call --> orders_exist: Existing Orders
        state "Orders Exist" as orders_exist
            orders_exist: filter.state = Delete
            orders_exist: Scratch.I = 0
            orders_exist: Scratch.FirstCall = False
            orders_exist: Memory.Command.Read Order Request = True
            orders_exist: Memory.Command.Read Order Address = 0
        first_call --> no_orders_exist: No Existing Orders
        state "No Orders Exist" as no_orders_exist
            no_orders_exist: filter.state = Wait.for.Command

    'orders_exist --> delete_order ' Leaf
    'no_orders_exist --> [*]

    delete_order --> check_memory: Scratch.FirstCall == False
    state "Check Memory" as check_memory: Is 'Memory.Command.Read Order Valid' True?
        check_memory --> clear_reads: Memory is not Ready
        state "Clear Reads" as clear_reads: filter.state = Delete
        state "Clear Reads" as clear_reads: Memory.Command.Read Order Request = False
        check_memory --> check_mode
        state "Check Mode" as check_mode
            check_mode --> state_shift
            state "state: Shift" as state_shift
                state_shift --> shift_is_last
                state "Is Last" as shift_is_last
                state_shift --> shift_not_last
                state "Not Last" as shift_not_last
            check_mode --> state_search
            state "state: Search" as state_search
                state_search --> order_id_matches
                state "OrderId Match" as order_id_matches
                    order_id_matches --> order_is_last
                    state "Is Last" as order_is_last
                    order_id_matches --> order_is_not_last
                    state "Is Not Last" as order_is_not_last
                state_search --> order_id_no_match
                state "OrderId Does Not Match" as order_id_no_match
                    order_id_no_match --> norder_is_last
                    state "Is Last" as norder_is_last
                    order_id_no_match --> norder_is_not_last
                    state "Is Not Last" as norder_is_not_last
}}
]

@enduml