@startuml 07_delete_order_act
hide empty description

title Delete_Order

while (State) is (Delete.Order)
    if (is First Call?) then (Yes)
        if (Orders Exist?) then (Yes)
            :Request First;
        else (No)
            stop
        endif
    else (No)
        if (Check Memory) then (Memory not Ready)
             :Clear Request;
        else
            if (Check Mode)
                :mode Search;
                if (OrderId Matches)
                    :Yes;
                    if ()
                        :Is Last;
                        stop
                    else
                        :Is Not Last;
                    endif
                else
                    :No;
                    if ()
                        :Is Last;
                        stop
                    else
                        :Is Not Last;
                    endif
                endif
            else
                :mode Shift;
                if ()
                    :Is Last;
                    stop
                else
                    :Is Not Last;
                endif
            endif
        endif
    endif
endwhile (Other)
stop

@enduml