@startuml Delete_Order
hide empty description

title Delete_Order


[*] --> is_first_call

state "Is First Call?" as is_first_call
state "Are there 0 Orders?" as are_there_zero
state "Cancel Reads" as cancel_reads: Request.Read == 0

state "What is current Mode?" as what_is_mode
state "Is Current Order a Match?" as is_current_match

is_first_call --> are_there_zero : Yes
are_there_zero --> cancel_reads
is_first_call --> what_is_mode : No

what_is_mode --> is_current_match
'SOO --> [*]

'state ProcessingTask {
'  [*] --> long1
'  long1 --> ProcessData : Enough Data
'}
'ProcessingTask -> [*]

@enduml